apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050 #in case anything else (other pod) needs to raach multi-client pod
      targetPort: 3000 #send incoming traffic to
      nodePort: 31515 #access point from outside
  selector:
    component: web